### PR TITLE
setup.py: update of URL and authors/maintainers

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
@chrisburr, would you consider updating the info in the setup.py file as follows? Seems nicer to me for a community package.
I fixed the URL in any case.
There is also the issue of the license. I would push for a BSD-3 license as we have for all Scikit-HEP projects, where possible. Could you give that a thought? This would require some additions as a 1-line header to the various files, see the other projects ...
Let me know :-). Thanks.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Any comments @chrisburr ?

**Comment by chrisburr** [comment]
I wasn't aware of the maintainer field but yes this is a nicer.

@ibab As this package is mostly your work, do you have any objections to it being BSD-3 instead of MIT to be more consistent with other scikit-hep packages?

**Comment by eduardo-rodrigues** [comment]
Shall we just create an issue for the question about licensing and accept this PR? Seems the way to go :-).

**Comment by chrisburr** [comment]
Yes!

**Pull request merged**
