### PR TITLE
changed the default value of the name of the TTree created by to_root

### PR DESCRIPTION
**Pull request by ttekampe**
`default` is a c++ key word and therefore not a good choice for the name of a TTree

### CODE REVIEW

**Comment by MaxNoe** [comment]
DecayTree seems to be Really application specific. Does not seem to be a good default at all.

**Comment by ttekampe** [comment]
Ok I dont care about the default value of the name. Its just that if it is a c++ keyword, you can run into troubles when opening the file in an interactive ROOT session.

So if you like we can call it `my_ttree`

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, is this not ready to be merged ;-)?

**Comment by chrisburr** [comment]
Yes it is! Thank you @ttekampe 👍

**Pull request merged**
